### ISSUE TITLE
gpt-3.5-turbo-16k not working

### ISSUE THREAD

**Issue by gtroisi** [andylokandy/gpt-4-search#2]
Hi, I'm trying to use gpt-3.5-turbo-16k to reduce costs, but I receive the following timeout error.

SEARCH("xxxxxxx")
Traceback (most recent call last):
  File "/Users/gabriele/Downloads/LLM/gpt-4-search-main/gpt-4-search.py", line 286, in <module>
    run(user_input)
  File "/Users/gabriele/Downloads/LLM/gpt-4-search-main/gpt-4-search.py", line 260, in run
    result = tool["run"](func_args)
  File "/Users/gabriele/Downloads/LLM/gpt-4-search-main/gpt-4-search.py", line 95, in search
    results = GoogleSearchAPIWrapper().results(query, 5)
  File "/Users/gabriele/miniforge3/envs/perplexity/lib/python3.10/site-packages/langchain/utilities/google_search.py", line 117, in results
    results = self._google_search_results(query, num=num_results)
  File "/Users/gabriele/miniforge3/envs/perplexity/lib/python3.10/site-packages/langchain/utilities/google_search.py", line 63, in _google_search_results
    res = cse.list(q=search_term, cx=self.google_cse_id, **kwargs).execute()
  File "/Users/gabriele/miniforge3/envs/perplexity/lib/python3.10/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/gabriele/miniforge3/envs/perplexity/lib/python3.10/site-packages/googleapiclient/http.py", line 923, in execute
    resp, content = _retry_request(
  File "/Users/gabriele/miniforge3/envs/perplexity/lib/python3.10/site-packages/googleapiclient/http.py", line 222, in _retry_request
    raise exception
  File "/Users/gabriele/miniforge3/envs/perplexity/lib/python3.10/site-packages/googleapiclient/http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/Users/gabriele/miniforge3/envs/perplexity/lib/python3.10/site-packages/httplib2/__init__.py", line 1724, in request
    (response, content) = self._request(
  File "/Users/gabriele/miniforge3/envs/perplexity/lib/python3.10/site-packages/httplib2/__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/Users/gabriele/miniforge3/envs/perplexity/lib/python3.10/site-packages/httplib2/__init__.py", line 1366, in _conn_request
    conn.connect()
  File "/Users/gabriele/miniforge3/envs/perplexity/lib/python3.10/site-packages/httplib2/__init__.py", line 1156, in connect
    sock.connect((self.host, self.port))
TimeoutError: timed out

**Comment by andylokandy** [comment]
does gpt-4 work？
